package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/99designs/gqlgen/_examples/large-project-structure/main/private/graph/model"
	"github.com/99designs/gqlgen/_examples/large-project-structure/shared/graph"
)

// PushIntel is the resolver for the pushIntel field.
func (r *mutationResolver) PushIntel(ctx context.Context, input model.SubmitIntel) (*model.SubmitIntelResponse, error) {
	fmt.Println("PRIVATE PUSH INTEL")
	return &model.SubmitIntelResponse{
		Success:          true,
		VerificationCode: "23-3klj-234lalake",
	}, nil
}

// ProcessFile is the resolver for the processFile field.
func (r *mutationResolver) ProcessFile(ctx context.Context, input model.ProcessFileSource) (*model.GeneralMessage, error) {
	fmt.Printf("Processing files %s \n", input.Dir)
	// See where to grab the file, incorrectly name dir >.>
	filepath := input.Dir

	f, err := os.Open(filepath)
	if err != nil {
		return nil, fmt.Errorf("cant read %q: %w", filepath, err)
	}
	defer f.Close()

	fmt.Println("Getting Scanner")

	// Read line by line
	scanner := bufio.NewScanner(f)
	fmt.Println("scanning")
	for scanner.Scan() {
		line := scanner.Text()
		var hd map[string]any
		if err := json.Unmarshal([]byte(line), &hd); err != nil {
			fmt.Println("errrrrrr", err)
			return nil, fmt.Errorf("unable to unmarshal %s: %w", line, err)
		}

		fmt.Printf("FLEET PICKED UP: %s \n", hd["serial_number"])
	}
	if err := scanner.Err(); err != nil {
		fmt.Printf("Scanner error: %v\n", err)
		return nil, fmt.Errorf("error reading file: %w", err)
	}
	msg := "We got your file...to the DB"
	return &model.GeneralMessage{
		Success: true,
		Message: &msg,
	}, nil
}

// GetConnector is the resolver for the getConnector field.
func (r *queryResolver) GetConnector(ctx context.Context, id int32) (*model.Connector, error) {
	fmt.Println("PRIVATE GET CONNECTOR")
	connectors := map[int32]*model.Connector{
		1: {
			ID:   1,
			Name: "CrowdStrike Falcon",
			Config: graph.JSON{
				"clientID":     "5f327e7c18224603ae70cb85653d8a8b",
				"clientSecret": "6MeQoCOW4d5T70t1kRSZa32Kni9EYXPfmGLAywc8",
				"cloud":        "us-1",
			},
		},
	}
	// Lets lookup in our map first
	if connInfo, ok := connectors[id]; ok {
		fmt.Println("found: ", connInfo)
		return connInfo, nil
	}

	// Pretend we couldn't find anything
	return nil, nil
}

// GetFromExternal is the resolver for the getFromExternal field.
func (r *queryResolver) GetFromExternal(ctx context.Context) (string, error) {
	fmt.Println("Our MAIN private graph will try to fetch from CRWD Private graph...")
	return "not toady", nil
}

// GetInside is the resolver for the getInside field.
func (r *queryResolver) GetInside(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: GetInside - getInside"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
