// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/_examples/large-project-structure/shared/graph"
)

type AuthInfo interface {
	IsAuthInfo()
	GetType() AuthType
}

type ConnectionInfo interface {
	IsConnectionInfo()
	GetID() string
	GetType() ConnectorType
	GetAuthInfo() AuthInfo
}

type ZeekIntel interface {
	IsZeekIntel()
	GetID() string
	GetName() string
}

type Basic struct {
	Username string  `json:"username"`
	Password *string `json:"password,omitempty"`
}

type BasicAuthInfo struct {
	Type   AuthType `json:"type"`
	Config *Basic   `json:"config"`
}

func (BasicAuthInfo) IsAuthInfo()            {}
func (this BasicAuthInfo) GetType() AuthType { return this.Type }

type Connector struct {
	ID     int32      `json:"id"`
	Name   string     `json:"name"`
	Config graph.JSON `json:"config"`
}

type ContentUpdatePolicy struct {
	Applied            *bool   `json:"applied,omitempty"`
	AppliedDate        *string `json:"appliedDate,omitempty"`
	AssignedDate       *string `json:"assignedDate,omitempty"`
	LastEvaluationDate *string `json:"lastEvaluationDate,omitempty"`
	PolicyID           *string `json:"policyId,omitempty"`
	PolicyType         *string `json:"policyType,omitempty"`
	RuleGroups         *string `json:"ruleGroups,omitempty"`
	SettingsHash       *string `json:"settingsHash,omitempty"`
}

type CrowdStrikeFalconConnection struct {
	ID       string                  `json:"id"`
	Type     ConnectorType           `json:"type"`
	AuthInfo AuthInfo                `json:"authInfo,omitempty"`
	Cloud    *CrowdStrikeFalconCloud `json:"cloud,omitempty"`
}

func (CrowdStrikeFalconConnection) IsConnectionInfo()           {}
func (this CrowdStrikeFalconConnection) GetID() string          { return this.ID }
func (this CrowdStrikeFalconConnection) GetType() ConnectorType { return this.Type }
func (this CrowdStrikeFalconConnection) GetAuthInfo() AuthInfo  { return this.AuthInfo }

type DevicePolicies struct {
	ContentUpdate *ContentUpdatePolicy `json:"contentUpdate,omitempty"`
}

type GeneralMessage struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type HostDetail struct {
	AgentLoadFlags       *string         `json:"agentLoadFlags,omitempty"`
	AgentLocalTime       *string         `json:"agentLocalTime,omitempty"`
	AgentVersion         *string         `json:"agentVersion,omitempty"`
	BiosManufacturer     *string         `json:"biosManufacturer,omitempty"`
	BiosVersion          *string         `json:"biosVersion,omitempty"`
	ChassisType          *string         `json:"chassisType,omitempty"`
	ChassisTypeDesc      *string         `json:"chassisTypeDesc,omitempty"`
	Cid                  *string         `json:"cid,omitempty"`
	ConfigIDBase         *string         `json:"configIdBase,omitempty"`
	ConfigIDBuild        *string         `json:"configIdBuild,omitempty"`
	ConfigIDPlatform     *string         `json:"configIdPlatform,omitempty"`
	ConnectionIP         *string         `json:"connectionIp,omitempty"`
	ConnectionMacAddress *string         `json:"connectionMacAddress,omitempty"`
	CPUSignature         *string         `json:"cpuSignature,omitempty"`
	CPUVendor            *string         `json:"cpuVendor,omitempty"`
	DefaultGatewayIP     *string         `json:"defaultGatewayIp,omitempty"`
	DeploymentType       *string         `json:"deploymentType,omitempty"`
	DeviceID             *string         `json:"deviceId,omitempty"`
	DevicePolicies       *DevicePolicies `json:"devicePolicies,omitempty"`
}

type Mutation struct {
}

type NoAuthInfo struct {
	Type AuthType `json:"type"`
}

func (NoAuthInfo) IsAuthInfo()            {}
func (this NoAuthInfo) GetType() AuthType { return this.Type }

type OAuth2 struct {
	ClientID    string `json:"clientId"`
	ClientToken string `json:"clientToken"`
}

type OAuth2AuthInfo struct {
	Type   AuthType `json:"type"`
	Config *OAuth2  `json:"config"`
}

func (OAuth2AuthInfo) IsAuthInfo()            {}
func (this OAuth2AuthInfo) GetType() AuthType { return this.Type }

type ProcessFileSource struct {
	Type FileSourceType `json:"type"`
	Dir  string         `json:"dir"`
}

type Query struct {
}

type SubmitIntel struct {
	Name     string `json:"name"`
	IntelID  int32  `json:"intelID"`
	Filepath string `json:"filepath"`
}

type SubmitIntelResponse struct {
	Success          bool   `json:"success"`
	VerificationCode string `json:"verificationCode"`
}

type FetchCrowdStrikeIntelInput struct {
	URL     string  `json:"url"`
	Option1 *string `json:"option1,omitempty"`
	Option2 *string `json:"option2,omitempty"`
}

type AuthType string

const (
	AuthTypeOauth2 AuthType = "OAUTH2"
	AuthTypeBasic  AuthType = "BASIC"
	AuthTypeNone   AuthType = "NONE"
)

var AllAuthType = []AuthType{
	AuthTypeOauth2,
	AuthTypeBasic,
	AuthTypeNone,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeOauth2, AuthTypeBasic, AuthTypeNone:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ConnectorType string

const (
	ConnectorTypeAlienvault        ConnectorType = "ALIENVAULT"
	ConnectorTypeCrowdstrikeFalcon ConnectorType = "CROWDSTRIKE_FALCON"
	ConnectorTypeMandiant          ConnectorType = "MANDIANT"
	ConnectorTypeValhalla          ConnectorType = "VALHALLA"
)

var AllConnectorType = []ConnectorType{
	ConnectorTypeAlienvault,
	ConnectorTypeCrowdstrikeFalcon,
	ConnectorTypeMandiant,
	ConnectorTypeValhalla,
}

func (e ConnectorType) IsValid() bool {
	switch e {
	case ConnectorTypeAlienvault, ConnectorTypeCrowdstrikeFalcon, ConnectorTypeMandiant, ConnectorTypeValhalla:
		return true
	}
	return false
}

func (e ConnectorType) String() string {
	return string(e)
}

func (e *ConnectorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectorType", str)
	}
	return nil
}

func (e ConnectorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CrowdStrikeFalconCloud string

const (
	CrowdStrikeFalconCloudUs1    CrowdStrikeFalconCloud = "US_1"
	CrowdStrikeFalconCloudUs2    CrowdStrikeFalconCloud = "US_2"
	CrowdStrikeFalconCloudEu1    CrowdStrikeFalconCloud = "EU_1"
	CrowdStrikeFalconCloudUsGov1 CrowdStrikeFalconCloud = "US_GOV_1"
)

var AllCrowdStrikeFalconCloud = []CrowdStrikeFalconCloud{
	CrowdStrikeFalconCloudUs1,
	CrowdStrikeFalconCloudUs2,
	CrowdStrikeFalconCloudEu1,
	CrowdStrikeFalconCloudUsGov1,
}

func (e CrowdStrikeFalconCloud) IsValid() bool {
	switch e {
	case CrowdStrikeFalconCloudUs1, CrowdStrikeFalconCloudUs2, CrowdStrikeFalconCloudEu1, CrowdStrikeFalconCloudUsGov1:
		return true
	}
	return false
}

func (e CrowdStrikeFalconCloud) String() string {
	return string(e)
}

func (e *CrowdStrikeFalconCloud) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CrowdStrikeFalconCloud(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CrowdStrikeFalconCloud", str)
	}
	return nil
}

func (e CrowdStrikeFalconCloud) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FileSourceType string

const (
	FileSourceTypeInput         FileSourceType = "INPUT"
	FileSourceTypeIntelRules    FileSourceType = "INTEL_RULES"
	FileSourceTypeSuricataRules FileSourceType = "SURICATA_RULES"
)

var AllFileSourceType = []FileSourceType{
	FileSourceTypeInput,
	FileSourceTypeIntelRules,
	FileSourceTypeSuricataRules,
}

func (e FileSourceType) IsValid() bool {
	switch e {
	case FileSourceTypeInput, FileSourceTypeIntelRules, FileSourceTypeSuricataRules:
		return true
	}
	return false
}

func (e FileSourceType) String() string {
	return string(e)
}

func (e *FileSourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileSourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileSourceType", str)
	}
	return nil
}

func (e FileSourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
