package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/99designs/gqlgen/_examples/large-project-structure/integration/private/graph/model"
	priv_fleet "github.com/99designs/gqlgen/_examples/large-project-structure/main/private/graph"
	fleet_models "github.com/99designs/gqlgen/_examples/large-project-structure/main/private/graph/model"
	"github.com/crowdstrike/gofalcon/falcon"
	"github.com/crowdstrike/gofalcon/falcon/client"
	"github.com/crowdstrike/gofalcon/falcon/client/hosts"
	"github.com/crowdstrike/gofalcon/falcon/models"
	"github.com/crowdstrike/gofalcon/pkg/falcon_util"
)

// FetchCrowdStrikeIntel is the resolver for the fetchCrowdStrikeIntel field.
func (r *Resolver) FetchCrowdStrikeIntel(ctx context.Context, input *fleet_models.FetchCrowdStrikeIntelInput) (*fleet_models.GeneralMessage, error) {
	fmt.Println("INTEGRATION PRIVATE FETCCCCCHHHH CRWD 👊")
	msg := "you are receiving an internal message from the integration private graph!"
	return &fleet_models.GeneralMessage{
		Success: true,
		Message: &msg,
	}, nil
}

func getCrowdStrikeConnector(ctx context.Context, connectorID int32) (*fleet_models.Connector, error) {
	fleetPriv := priv_fleet.QResolver{}
	conn, err := fleetPriv.GetConnector(ctx, connectorID)
	if err != nil {
		return nil, fmt.Errorf("yo, fleet cant find that: %w", err)
	}

	return conn, nil
}

func getHostIds(client *client.CrowdStrikeAPISpecification, filter *string) <-chan []string {
	hostIds := make(chan []string)

	go func() {
		limit := int64(5000)
		for offset := ""; ; {
			response, err := client.Hosts.QueryDevicesByFilterScroll(&hosts.QueryDevicesByFilterScrollParams{
				Context: context.Background(),
				Limit:   &limit,
				Offset:  &offset,
				Filter:  filter,
			})
			if err != nil {
				panic(falcon.ErrorExplain(err))
			}
			if err = falcon.AssertNoError(response.Payload.Errors); err != nil {
				panic(err)
			}

			hosts := response.Payload.Resources
			if len(hosts) == 0 {
				break
			}

			hostIds <- hosts

			if *response.Payload.Meta.Pagination.Offset == "" || int64(len(hosts)) < limit {
				break // no more next page indicates we are done
			}

			offset = *response.Payload.Meta.Pagination.Offset
		}
		close(hostIds)
	}()
	return hostIds
}

func getHostsDetails(client *client.CrowdStrikeAPISpecification, hostIds []string) []*models.DeviceapiDeviceSwagger {
	response, err := client.Hosts.PostDeviceDetailsV2(&hosts.PostDeviceDetailsV2Params{
		Body:    &models.MsaIdsRequest{Ids: hostIds},
		Context: context.Background(),
	})
	if err != nil {
		panic(falcon.ErrorExplain(err))
	}
	if err = falcon.AssertNoError(response.Payload.Errors); err != nil {
		panic(err)
	}

	return response.Payload.Resources
}

func getHostDetails(conn *fleet_models.Connector, fileDir string) ([]*model.HostDetail, error) {
	fmt.Println("getting connection info")
	// Safely cast the values to strings
	clientID, ok := conn.Config["clientID"].(string)
	if !ok {
		return nil, fmt.Errorf("clientID is not a string: %d", conn.ID)
	}

	clientSecret, ok := conn.Config["clientSecret"].(string)
	if !ok {
		return nil, fmt.Errorf("clientSecret is not a string: %d", conn.ID)
	}

	cloud, ok := conn.Config["cloud"].(string)
	if !ok {
		return nil, fmt.Errorf("cloud is not a string: %d", conn.ID)
	}

	fmt.Println("getting falcon client")
	client, err := falcon.NewClient(&falcon.ApiConfig{
		ClientId:     clientID,
		ClientSecret: clientSecret,
		// MemberCID:    *memberCID,
		Cloud:   falcon.Cloud(cloud),
		Context: context.Background(),
	})
	if err != nil {
		return nil, fmt.Errorf("shoot, the client is no good: %w", err)
	}

	fmt.Println("making workspace")
	f, err := os.CreateTemp(fileDir, "input-crowdstrike-%")
	if err != nil {
		return nil, fmt.Errorf("cound't create temp crwd file: %w", err)
	}
	defer f.Close()

	fmt.Println("getting crwd host ids")
	empty := true
	for hostIdBatch := range getHostIds(client, nil) {
		if len(hostIdBatch) == 0 {
			continue
		}
		fmt.Printf("getting crwd host details for batch %s\n", hostIdBatch)
		hostDetailBatch := getHostsDetails(client, hostIdBatch)
		for _, host := range hostDetailBatch {
			fmt.Printf("details for host %s\n", host.InstanceID, host.Cid)
			j, err := falcon_util.PrettyJson(host)
			if err != nil {
				panic(err)
			}
			if !empty {
				j = "," + j
			} else {
				empty = false
			}

			fmt.Println(j)

			// Just going to add this hear to write to the file
			hostDetail, err := json.Marshal(host)
			if err != nil {
				return nil, fmt.Errorf("failed to marshal json:", err)
			}

			_, err = f.Write(hostDetail)
			_, err = f.WriteString("\n")
			if err != nil {
				return nil, fmt.Errorf("couldn't write json: %w", err)
			}
		}
	}

	// Can we call Fleet to let it know about the data?
	prvFleet := priv_fleet.MResolver{}
	fileSource := fleet_models.ProcessFileSource{
		Type: fleet_models.FileSourceTypeInput,
		Dir:  f.Name(),
	}

	// We need to close the file
	f.Close()

	msg, err := prvFleet.ProcessFile(context.Background(), fileSource)
	if err != nil {
		return nil, fmt.Errorf("...log the error: %w", err)
	}
	fmt.Println("msg", msg)

	return nil, nil
}

// FetchCrowdStrikeHostDetailDirect is the resolver for the fetchCrowdStrikeHostDetailDirect field.
func (r *Resolver) FetchCrowdStrikeHostDetailDirect(ctx context.Context, connectorID int32) ([]*fleet_models.HostDetail, error) {
	// There are a few paths we could take, this could take a connector fully populated...
	// it could take a connectionID to look up auth from a service (Fleet for now)
	// This should be thought through what it he most ideal way to communicate bewteen
	// Suri updater gets handed auth..
	conn, err := getCrowdStrikeConnector(ctx, connectorID)
	if err != nil {
		return nil, err
	}
	fmt.Println("conn:", conn)
	panic(fmt.Errorf("not implemented: FetchCrowdStrikeHostDetailDirect - fetchCrowdStrikeHostDetailDirect"))
}

// FetchCrowdStrikeHostDetail is the resolver for the fetchCrowdStrikeHostDetail field.
func (r *Resolver) FetchCrowdStrikeHostDetail(ctx context.Context, connectorID int32) (*fleet_models.GeneralMessage, error) {
	// There are a few paths we could take, this could take a connector fully populated...
	// it could take a connectionID to look up auth from a service (Fleet for now)
	// This should be thought through what it he most ideal way to communicate bewteen
	// Suri updater gets handed auth..
	conn, err := getCrowdStrikeConnector(ctx, connectorID)
	if err != nil {
		return nil, err
	}

	// Start the async process...or add to queue...throttle?
	go getHostDetails(conn, r.InputDir)

	msg := "Started processing host detail"
	return &fleet_models.GeneralMessage{
		Success: true,
		Message: &msg,
	}, nil
}

// GetInside is the resolver for the getInside field.
func (r *Resolver) GetInside(ctx context.Context) (string, error) {
	fmt.Println("INTEGATION PRIVATE GET INSIDE")
	return "You are inside the private graph for integration package", nil
}
